### PR TITLE
Automatic bridge discovery

### PR DESCRIPTION
**Pull request by madmod**
I will be adding bridge ip address discovery ~~and “user” registration~~. (Edit: I think I will save that for another PR because I have some other things to work on.) I also want to save the ip in the config.json but modifying a settings file feels like a hack.

### CODE REVIEW

**Comment by madmod** [comment]
Also my previous fix for saturation was unnecessary because node-hue-api has functions that take percentages.

**Comment by madmod** [comment]
It works for me with my bridge registered at meethue.com. I will test it with scanning and no bridges manually now.

**Comment by madmod** [comment]
I think this is ready now. :smiley: 
Both kinds of discovery work. The network scan takes a few seconds more on my network than the meethue.com API. The meethue.com API is fast enough that I don't think saving is important anymore unless you have multiple bridges or UPnP problems. If someone really wants to shave a second off startup then the log messages will give them the bridge ip.

**Comment by stephenyeargin** [comment]
:metal: I'm a bit of a novice on what this procedurally related to setup in HomeKit ... I'm guessing the IP address no longer has to be added to the JSON if you go this route? Or does it remove the need for the JSON config options entirely?

**Comment by stephenyeargin** [comment]
Ah, I see the updated description now. I'm good with it.

**Comment by madmod** [comment]
This makes registering the ip address in the JSON file optional. If you have multiple bridges or no UPnP support on your network then you would still need to add it manually. I hope to have a future PR for registering the "user" by asking them to press the link button.

**Pull request merged**
