### PR TITLE
Report initial state, refactor code a bit

### PR DESCRIPTION
**Pull request by stephenyeargin**
- The initial state of the device is now reported on connection
- Properly detects what should happen with Hue/Hue Lux bulbs (removes the extra characteristics)
- Scales values a bit more transparently so the color gets a bit closer
- Moved `execute` method inside the accessory model for clearer designation
- Cleaned up that ridiculous `if/else` block into a switch

/cc @madmod

### CODE REVIEW

**Comment by stephenyeargin** [comment]
If this one works, we'll have cleared all the checkboxes on https://github.com/nfarina/homebridge/pull/28 and a few unexpected ones along the way.

**Comment by madmod** [comment]
Looks great! I will give it a try now.

**Comment by madmod** [comment]
Looks like I do need to reset HomeKit on my iPhone. (just fyi)

**Comment by madmod** [comment]
Hmm I'm not seeing my lights in the Insteon+ app anymore but they show up in the log. I will try reinstalling the app.

**Comment by stephenyeargin** [comment]
Yeah, I had to start fresh from the `persist` directory and reset Homekit. Entirely the fault of the (corrected Serial Number.

**Comment by madmod** [comment]
Okay I'll do that.

**Comment by madmod** [comment]
Works great! :+1: The status shows in the insteon app when I load it. I think one more task we might consider in the future if we can find a way to do it without constantly polling the API would be to reflect the current state in HomeKit apps when it changes from another system like Hue Tap.

**Comment by stephenyeargin** [comment]
Definitely. Hoping a lower-level service in Homebridge itself could handle that at some level (re-poll the initial state). As with all the shims, we're all really just hoping Philips handles it themselves :grinning:

**Comment by madmod** [comment]
haha right. I'm on to making a shim for my Logitech Harmony remote! :smile:

**Pull request merged**
